name: xalq_nazorati
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^4.0.4
  image_picker: ^0.6.7+7
  http: ^0.12.2
  provider: ^4.3.2+1
  flutter_svg: ^0.18.1
  awesome_dialog: ^1.2.0
  bottom_navy_bar: ^5.4.0
  group_radio_button: ^1.0.1
  dotted_border: ^1.0.6
  custom_navigator: 
    git:
        url: https://github.com/kjawadDeveloper/Custom-navigator.git 
  permission_handler: ^5.0.1+2
  shared_preferences: ^0.5.10
  easy_localization: ^2.3.3
  geolocator: ^6.0.0+4
  intl: ^0.16.1
  flutter_html: ^1.0.2
  requests: ^3.3.0
  mask_text_input_formatter: ^1.1.0
  scroll_to_index: ^1.0.6
  smooth_star_rating: 1.1.1
  file_picker: ^2.0.7
  url_launcher: ^5.7.5
  path_provider: ^1.6.7
  fluttertoast: ^7.1.1
  
  flutter_mrz_scanner: ^1.0.0+3
  camera: ^0.5.8+9
  image: ^2.1.18
  firebase_ml_vision: ^0.9.7
  flutter_masked_text: ^0.8.0
  firebase_core: ^0.5.0+1
  
  yandex_mapkit: ^0.4.0
  
  share: ^0.6.5+4
  in_app_review: ^1.0.4
  flutter_local_notifications: ^3.0.1+2
  firebase_messaging: ^7.0.3
  advance_pdf_viewer: ^1.2.0
  no_context_navigation: ^1.0.3
  expandable: ^4.1.4
  carousel_slider: ^2.3.1
  scrollable_positioned_list: ^0.1.8
  indexed_list_view: ^1.1.5
  platform_inputs: ^0.0.2
  flashlight: ^0.1.1
  cached_network_image: ^2.4.1
  sms_autofill: ^1.2.7
  flutter_image_compress: ^0.7.0
  liquid_progress_indicator: ^0.3.2
  # internet_speed_test: ^1.1.2+1
  connectivity: ^2.0.2
  keyboard_actions: ^3.3.1+1
  data_connection_checker: ^0.3.4
  sms_otp_auto_verify: ^1.2.2
  skeleton_text: ^1.0.0
  # sms_retriever: ^0.0.2
  pull_to_refresh: ^1.6.3
  lazy_load_scrollview: ^1.2.0
  is_lock_screen: ^1.0.0
  overlay_support: ^0.0.4
  soundpool: ^1.0.1
  # workmanager: ^0.2.3
  catcher: ^0.4.1
  system_settings: ^1.0.1
  easy_permission_validator: ^2.0.1
  
  # sms:
  #   path: ./sms

  flutter_typeahead: 
    path: ./flutter_typeahead
  # lamp: 
  #   path: ./lamp




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1
  flutter_launcher_icons: ^0.7.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/launcher.png"
  image_path_android: "assets/launcher/launcher.png"
  image_path: "assets/launcher/launcher.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #localozation files
    - lang/uz-UZ.json
    - lang/ru-RU.json
    - lang/en-US.json
    # image in app
    - assets/img/logo.svg
    - assets/img/Frame.svg
    - assets/img/FrameW.svg
    - assets/img/Passport.svg
    - assets/img/home.svg
    - assets/img/profile.svg
    - assets/img/support.svg
    - assets/img/problem.svg
    
  
    - assets/img/location.svg
    - assets/img/support.png

    - assets/img/profile_icon.svg
    - assets/img/lang_icon.svg
    - assets/img/info_icon.svg
    - assets/img/quit_icon.svg

    - assets/img/share_icon.svg
    - assets/img/rate_icon.svg
    - assets/img/support_icon.svg
    - assets/img/rule_icon.svg
    - assets/img/warning.svg
    - assets/img/plus_icon.svg
    - assets/img/finish.svg
    - assets/img/men_icon.svg
    - assets/img/image.svg
    - assets/img/camera.svg
    - assets/img/locate.svg

    - assets/img/newsLocate.svg
    - assets/img/newsClock.svg
    - assets/img/facebook.svg
    - assets/img/instagram.svg
    - assets/img/twitter.svg
    - assets/img/telegram.svg
    
    - assets/img/bell.svg
    - assets/img/pdf.png

    - assets/img/user.svg
    - assets/img/calendar.svg
    - assets/img/pin.svg
    
    - assets/img/send_icon.svg
    - assets/img/file_icon.svg
    - assets/img/qr-code-scan.svg
    - flutter_assets/placemark.png
    - assets/img/info.svg
    - assets/img/iPhone11.png
    - assets/img/eye_open.svg
    - assets/img/eye_close.svg
    - assets/img/ques.svg
    - assets/img/news_bg.svg
    - assets/img/news_complete.svg
    - assets/img/news_proccess.svg
    - assets/img/news_breaking.svg
    - assets/img/news_planned.svg
    - assets/img/news_archive.svg
    - assets/img/user_main.svg
    - assets/img/dont_men.svg
    - assets/img/offline.png
    - assets/img/play.svg
    
    - assets/img/no_connection.svg
    - assets/img/bad_connection.svg
    - assets/img/good_connection.svg

    - assets/material.png
    - assets/audios/


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 900
        # - asset: assets/fonts/Gilroy-Black.ttf
        #   weight: 900
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
